# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:11
from __future__ import unicode_literals

import core.fields.array_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinesweeperGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_over', models.BooleanField(default=False)),
                ('board', core.fields.array_field.ArrayField(default=((0.0,),), max_length=5000)),
                ('cell_states', core.fields.array_field.ArrayField(default=((0.0,),), max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
